/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_zjf_ffmpegcommand_MainActivity */

#ifndef _Included_com_example_zjf_ffmpegcommand_MainActivity
#define _Included_com_example_zjf_ffmpegcommand_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_zjf_ffmpegcommand_MainActivity
 * Method:    avformatInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zjf_ffmpegcommand_MainActivity_avformatInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zjf_ffmpegcommand_MainActivity
 * Method:    avCodecInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zjf_ffmpegcommand_MainActivity_avCodecInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zjf_ffmpegcommand_MainActivity
 * Method:    avFilterInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zjf_ffmpegcommand_MainActivity_avFilterInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_zjf_ffmpegcommand_MainActivity
 * Method:    configInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_zjf_ffmpegcommand_MainActivity_configInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
